src/CANICA/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from nino import  views

urlpatterns = [
    path('reporte/', include('nino.urls')),
    path('noticia/', include('noticia.urls')),
    path('calendario/',views.calendario, name='calendario'),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/nino/urls.py
from django.urls import path

from . import views

app_name="nino"
urlpatterns = [
    path("",views.NNAListView.as_view(),name="list"),
]

src/noticia/urls.py
from django.urls import path

from . import views
app_name="noticia"
urlpatterns = [
    path("",views.NoticiaListView.as_view(),name="noticia"),
    path("<int:pk>/", views.NoticiaDetailView.as_view(), name="detail"),
]

src/noticia/models.py
from django.db import models
from django import forms
# Create your models here.
class Noticia(models.Model):
    """Model definition for Noticia."""

    # TODO: Define fields here
    titulo_noticia=models.CharField(max_length=40,verbose_name="Título de la noticia")
    imagen=models.ImageField(upload_to="img",verbose_name="Fotografía de la notica")
    fecha_publicacion=models.DateField(auto_now_add=True,verbose_name="Fecha de publicación")
    descripcion=models.TextField(verbose_name="Descripción")


    class Meta:
        """Meta definition for Noticia."""

        verbose_name = 'Noticia'
        verbose_name_plural = 'Noticias'

    def __str__(self):
        return self.titulo_noticia+" "+str(self.fecha_publicacion)
    
    def get_absolute_url(self):
        return u'/noticia/%d' % self.id 

src/noticia/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views import generic
from .models import Noticia
# Create your views here.

class NoticiaListView(generic.ListView):
    model = Noticia
    template_name = "noticia.html"


class NoticiaDetailView(generic.DetailView):
    model = Noticia
    template_name = "detail.html"

src/noticia/templates/detail.html
<html>  
    <head>
        {% load static %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    </head>
    <body>
        <div class="col-md-5">
            <br>
                <div class="media">
                        <img src="{{ noticia.imagen.url }}" class="mr-3" width="200px">
                        <div class="media-body">
                          <h5 class="mt-0">{{ noticia.titulo_noticia }}</h5>
                          <p>{{ noticia.descripcion }}</p>
                          <a href="/noticia" class="btn btn-outline-primary">Regresar a noticias</a>
                        </div>
                      </div>
    </body>
</html>

src/noticia/templates/noticia.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Sección de noticias</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary">
        <a class="navbar-brand" href="/noticia">CANICA</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Inicio <span class="sr-only">(current)</span></a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <img src="{% static 'img/log.png' %}" width="100px">
          </form>
        </div>
      </nav>

    <center>
        <h1 style="color:blue"><strong>Sección de noticias</strong></h1>
    </center>
    <div class="col-md-5">
        <div class="card" style="width: 18rem;">
            {% for noticia in object_list %}
            <img src="{{noticia.imagen.url}}" class="card-img-top" width="200px">
            <div class="card-body">
              <h5 class="card-title">{{noticia.titulo_noticia}}</h5>
              <p class="card-text">{{noticia.fecha_publicacion}}</p>
              <a href="{% url 'noticia:detail' noticia.id %}" class="btn btn-outline-info">Mas información</a>
            </div>
            {% endfor %}
            <br>
          </div>

    </div>
</body>
</html>